#Weather Radar
- platform: generic
  still_image_url: https://radblast.wunderground.com/cgi-bin/radar/WUNIDS_map?station=OHX&brand=wui&num=10&delay=15&type=N0R&frame=0&scale=1.000&noclutter=1&showstorms=5&mapx=400&mapy=240&centerx=400&centery=240&transx=0&transy=0&showlabels=1&severe=0&rainsnow=0&lightning=0&smooth=0&rand=25283063&lat=0&lon=0&label=you
  name: radar
  scan_interval: 180

#MotionEyeOs Camera
- platform: generic
  still_image_url: !secret motioneye_url
  name: pi0_camera
  scan_interval: 1